wordpress:
  build: ./
  links:
    - db:mysql
  ports:
    - 8080:80
  volumes:
    - .:/var/www/html/wp-content/plugins/multi-site
  environment:
    - WORDPRESS_DEBUG=true

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: foo
